/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-09 08:19:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.MemberDAO;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.MemberDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/login.css\">\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("\r\n");
      out.write("display: block;\r\n");
      out.write("\r\n");
      out.write("text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link-up{\r\n");
      out.write("   color:#0B3861;\r\n");
      out.write("   text-decoration-line: none;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("   <script>\r\n");
      out.write("  \r\n");
      out.write("            window.Kakao.init(\"0e287908b28c66fab4de78695625ec5a\");//카카오 초기화\r\n");
      out.write("            window.Kakao.isInitialized();//카카오 API가 초기화되었는지를 확인하는 JavaScript 함수\r\n");
      out.write("            function kakaoLogin(){ //로그인기능\r\n");
      out.write("               window.Kakao.Auth.login({\r\n");
      out.write("                  scope:'profile_nickname,account_email',//로그인할때 내가 받아오는 값\r\n");
      out.write("                  success: function(authObj){\r\n");
      out.write("                     console.log(authObj);\r\n");
      out.write("                     window.Kakao.API.request({\r\n");
      out.write("                        url:'/v2/user/me',\r\n");
      out.write("                        success : res => {   //성공했을때 \r\n");
      out.write("                           const kakao_account=res.kakao_account;\r\n");
      out.write("                           console.log(kakao_account);\r\n");
      out.write("                        }\r\n");
      out.write("                  });\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("               });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function kakaoLogout() {\r\n");
      out.write("                 if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("                 Kakao.API.request({\r\n");
      out.write("                     url: '/v1/user/unlink',\r\n");
      out.write("                     success: function (authObj) {\r\n");
      out.write("                         console.log(authObj)\r\n");
      out.write("                     },\r\n");
      out.write("                     fail: function (error) {\r\n");
      out.write("                     console.log(error)\r\n");
      out.write("                     },\r\n");
      out.write("                 })\r\n");
      out.write("                 Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("                 alert(\"로그아웃 성공\");\r\n");
      out.write("                 }\r\n");
      out.write("             }  \r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("  <section class=\"home\">\r\n");
      out.write("    <h1>Welcome to the <span onclick=\"location.href='../main.jsp'\">PPLAN</span></h1>\r\n");
      out.write("    <button id=\"sign-up\" class=\"btn\">Sign Up</button>\r\n");
      out.write("    <button id=\"sign-in\" class=\"btn\">Log In</button>\r\n");
      out.write("    <p><a class=\"link-copy\">Trophy 2023</a></p>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <section class=\"sign-up\">\r\n");
      out.write("    <article class=\"signup-left\">\r\n");
      out.write("      <h1>PPLAN</h1>\r\n");
      out.write("      <div class=\"wc_message\">\r\n");
      out.write("        <h3>Let's PPLAN Now!</h3>\r\n");
      out.write("        <p>It's Easy and takes less then 30 seconds.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"btn-back\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"fas fa-2x fa-angle-left angle-left-color\"><img src=\"left.png\" width=\"30px\" height=\"30px\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"form-area\">\r\n");
      out.write("      <!-- Form area Sign Up -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"organize-form form-area-signup\">\r\n");
      out.write("        <h2>SIGN UP</h2>\r\n");
      out.write("        <form action=\"../../JoinService\" class=\"form\" method=\"post\">\r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"name\">ID</label>\r\n");
      out.write("            <input name =\"id\" type=\"text\" id=\"name\" /><span id=\"idCheck\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("         $(document).ready(function(){\r\n");
      out.write("               \r\n");
      out.write("               $(\"#name\").keyup(function(){\r\n");
      out.write("                  const idCheck = document.getElementById(\"idCheck\");\r\n");
      out.write("                  let inputId = $('#name').val();\r\n");
      out.write("                  \r\n");
      out.write("                  $.ajax({\r\n");
      out.write("                     url : \"../../idCheck\",\r\n");
      out.write("                     data : {\"id\" : inputId},\r\n");
      out.write("                     success : function(text){\r\n");
      out.write("                        \r\n");
      out.write("                        if(text===\"true\"){\r\n");
      out.write("                           idCheck.innerText = \"중복된 아이디입니다.\";\r\n");
      out.write("                        }else{\r\n");
      out.write("                           idCheck.innerText = \"사용 가능한 아이디입니다.\";\r\n");
      out.write("                        }\r\n");
      out.write("                     },\r\n");
      out.write("                     error : function(e){\r\n");
      out.write("                        console.log(e);\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("            });\r\n");
      out.write("         \r\n");
      out.write("         </script>\r\n");
      out.write("       \r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"password\">Password</label>\r\n");
      out.write("            <input name=\"pw\" type=\"password\" id=\"password\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"nick\">NickName</label>\r\n");
      out.write("            <input name=\"nick\" type=\"text\" id=\"nick\" /><span id=\"nickCheck\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("                  <script type=\"text/javascript\">\r\n");
      out.write("         $(document).ready(function(){\r\n");
      out.write("               \r\n");
      out.write("               $(\"#nick\").keyup(function(){\r\n");
      out.write("                  const nickCheck = document.getElementById(\"nickCheck\");\r\n");
      out.write("                  let inputNick = $(\"#nick\").val();\r\n");
      out.write("               \r\n");
      out.write("                  $.ajax({\r\n");
      out.write("                     url : \"../../nickCheck\",\r\n");
      out.write("                     data : {\"nick\" : inputNick},\r\n");
      out.write("                     success : function(text){\r\n");
      out.write("                        if(text===\"true\"){\r\n");
      out.write("                              nickCheck.innerText = \"중복된 닉네임입니다.\";\r\n");
      out.write("                        }else{\r\n");
      out.write("                           nickCheck.innerText = \"사용 가능한 닉네임입니다.\";\r\n");
      out.write("                        }\r\n");
      out.write("                     },\r\n");
      out.write("                     error : function(e){\r\n");
      out.write("                        console.log(e);\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("            });\r\n");
      out.write("         \r\n");
      out.write("         </script>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"email\">Email</label>\r\n");
      out.write("            <input name=\"email\" type=\"text\" id=\"email\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <button class=\"btn-sign btn-up\">Sign Up</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Form area Sign In -->\r\n");
      out.write("      <div class=\"organize-form form-area-signin\">\r\n");
      out.write("        <h2>Log IN</h2>\r\n");
      out.write("        <form action=\"../../LoginService\" method=\"post\" class=\"form\">\r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"email-in\">ID</label>\r\n");
      out.write("            <input type=\"text\" name=\"id\" id=\"email-in\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-field\">\r\n");
      out.write("            <label for=\"password-in\">Password</label>\r\n");
      out.write("            <input type=\"password\" name=\"pw\" id=\"password-in\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <button class=\"btn-sign btn-in\">Log In</button>\r\n");
      out.write("          <br>\r\n");
      out.write("          <br>\r\n");
      out.write("            <a href=\"javascript:kakaoLogin();\"><img src=\"kakao_login_medium_wide.png\" width=\"100%\"></a>\r\n");
      out.write("          <a href=\"javascript:kakaoLogout();\" class=\"link-up\">logout</a>\r\n");
      out.write("           <a href=\"#\" class=\"link-up\">Sign Up</a>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <article class=\"signup-right\">\r\n");
      out.write("      <i class=\"fas fa-2x fa-bars bars-style\"></i>\r\n");
      out.write("      <p><a class=\"link-copy\">Trophy 2023</a></p>\r\n");
      out.write("    </article>\r\n");
      out.write("  </section>\r\n");
      out.write("  <script type =\"text/javascript\"> \r\n");
      out.write(" const el = {\r\n");
      out.write("        signUpHome: document.getElementById('sign-up'),\r\n");
      out.write("        signInHome: document.getElementById('sign-in'),\r\n");
      out.write("        btnHome: document.querySelector('.btn-back'),\r\n");
      out.write("        pageMain: document.querySelector('.main'),\r\n");
      out.write("        pageHome: document.querySelector('.home'),\r\n");
      out.write("        pageSignUp: document.querySelector('.sign-up'),\r\n");
      out.write("        formArea: document.querySelector('.form-area'),\r\n");
      out.write("        sideSignLeft: document.querySelector('.signup-left'),\r\n");
      out.write("        sideSignRight: document.querySelector('.signup-right'),\r\n");
      out.write("        formSignUp: document.querySelector('.form-area-signup'),\r\n");
      out.write("        formSignIn: document.querySelector('.form-area-signin'),\r\n");
      out.write("        linkUp: document.querySelector('.link-up'),\r\n");
      out.write("        linkIn: document.querySelector('.link-in'),\r\n");
      out.write("        btnSignUp: document.querySelector('.btn-up'),\r\n");
      out.write("        btnSignIn: document.querySelector('.btn-in'),\r\n");
      out.write("        labels: document.getElementsByTagName('label'),\r\n");
      out.write("        inputs: document.getElementsByTagName('input'),\r\n");
      out.write("      };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // ADD Events\r\n");
      out.write("      // Show the page Sign Up\r\n");
      out.write("      el.signUpHome.addEventListener('click', function(e) {\r\n");
      out.write("        showSign(e, 'signup');\r\n");
      out.write("      });\r\n");
      out.write("      el.linkUp.addEventListener('click', function(e) {\r\n");
      out.write("        showSign(e, 'signup');\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Show the page sign in\r\n");
      out.write("      el.signInHome.addEventListener('click', function(e) {\r\n");
      out.write("        showSign(e, 'login');\r\n");
      out.write("      });\r\n");
      out.write("      el.btnSignUp.addEventListener('click', function(e) {\r\n");
      out.write("        showSign(e, 'login');\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Show the page Home\r\n");
      out.write("      el.btnHome.addEventListener('click', showHome);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // Functions Events\r\n");
      out.write("      // function to show screen Home\r\n");
      out.write("      function showHome(event) {\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("          el.sideSignLeft.style.padding = '0';\r\n");
      out.write("          el.sideSignLeft.style.opacity = '0';\r\n");
      out.write("          el.sideSignRight.style.opacity = '0';\r\n");
      out.write("          el.sideSignRight.style.backgroundPositionX = '235%';\r\n");
      out.write("\r\n");
      out.write("          el.formArea.style.opacity = '0';\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            el.pageSignUp.style.opacity = '0';\r\n");
      out.write("            el.pageSignUp.style.display = 'none';\r\n");
      out.write("            for (input of el.inputs)  {\r\n");
      out.write("              input.value = '';\r\n");
      out.write("            }\r\n");
      out.write("          }, 900);\r\n");
      out.write("\r\n");
      out.write("        }, 100);\r\n");
      out.write("\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("          el.pageHome.style.display = 'flex';\r\n");
      out.write("        },1100);\r\n");
      out.write("        \r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("          el.pageHome.style.opacity = '1';\r\n");
      out.write("        }, 1200);\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      // function to show screen Sign up/Sign in\r\n");
      out.write("      function showSign(event, sign) {\r\n");
      out.write("\r\n");
      out.write("        if (sign === 'signup') {\r\n");
      out.write("          el.formSignUp.style.display = 'flex';\r\n");
      out.write("          el.formSignIn.style.opacity = '0';\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            el.formSignUp.style.opacity = '1';\r\n");
      out.write("          }, 100);\r\n");
      out.write("          el.formSignIn.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("        } else {\r\n");
      out.write("          el.formSignIn.style.display = 'flex';\r\n");
      out.write("          el.formSignUp.style.opacity = '0';\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            el.formSignIn.style.opacity = '1';\r\n");
      out.write("          }, 100);\r\n");
      out.write("          el.formSignUp.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        el.pageHome.style.opacity = '0';\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("          el.pageHome.style.display = 'none';\r\n");
      out.write("        }, 700);\r\n");
      out.write("        \r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("          el.pageSignUp.style.display = 'flex';\r\n");
      out.write("          el.pageSignUp.style.opacity = '1';\r\n");
      out.write("          \r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            el.sideSignLeft.style.padding = '20px';\r\n");
      out.write("            el.sideSignLeft.style.opacity = '1';\r\n");
      out.write("            el.sideSignRight.style.opacity = '1';\r\n");
      out.write("            el.sideSignRight.style.backgroundPositionX = '230%';\r\n");
      out.write("\r\n");
      out.write("            el.formArea.style.opacity = '1';\r\n");
      out.write("          }, 10);\r\n");
      out.write("\r\n");
      out.write("        }, 900);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Behavior of the inputs and labels\r\n");
      out.write("      for (input of el.inputs) {\r\n");
      out.write("        console.log(input)\r\n");
      out.write("        input.addEventListener('keydown', function() {\r\n");
      out.write("          this.labels[0].style.top = '10px';\r\n");
      out.write("        });\r\n");
      out.write("        input.addEventListener('blur', function() {\r\n");
      out.write("          if (this.value === '') {\r\n");
      out.write("            this.labels[0].style.top = '25px';\r\n");
      out.write("          }\r\n");
      out.write("        })\r\n");
      out.write("      } \r\n");
      out.write("      \r\n");
      out.write(" </script>\r\n");
      out.write("</main>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
