/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 01:38:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.LocaDTO;
import com.model.LocaDAO;
import com.model.BadgeDTO;
import java.util.ArrayList;
import com.model.BadgeDAO;
import com.model.MemberDTO;
import java.net.URLEncoder;

public final class menu_005fmyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.LocaDAO");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.model.LocaDTO");
    _jspx_imports_classes.add("com.model.BadgeDTO");
    _jspx_imports_classes.add("com.model.BadgeDAO");
    _jspx_imports_classes.add("com.model.MemberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>마이페이지</title>\r\n");
      out.write("      <meta charset=\"EUC-KR\" />\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("      <noscript><link rel=\"stylesheet\" href=\"assets/css/noscript.css\" /></noscript>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body class=\"left-sidebar is-preload\">\r\n");
      out.write("      ");
 MemberDTO info = (MemberDTO)session.getAttribute("info"); 
      out.write("\r\n");
      out.write("      <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("         <!-- Header -->\r\n");
      out.write("            <div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("               <!-- Inner -->\r\n");
      out.write("                  <div class=\"inner\">\r\n");
      out.write("                     <header>\r\n");
      out.write("                        <h1><a href=\"main.jsp\" id=\"logo\">PPLAN</a></h1>\r\n");
      out.write("                        ");
if(info !=null){ 
      out.write("\r\n");
      out.write("                        <h3>");
      out.print(info.getId() );
      out.write("'s Page</h3>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                     </header>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- Nav -->\r\n");
      out.write("                  <nav id=\"nav\">\r\n");
      out.write("                     <ul>\r\n");
      out.write("                        <li><a href=\"main.jsp\">Home</a></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                           <a href=\"#\">Dropdown</a>\r\n");
      out.write("                           <ul>\r\n");
      out.write("                              <li><a href=\"#\">Lorem ipsum dolor</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Magna phasellus</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Etiam dolore nisl</a></li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                 <a href=\"#\">And a submenu &hellip;</a>\r\n");
      out.write("                                 <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Lorem ipsum dolor</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Phasellus consequat</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Magna phasellus</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Etiam dolore nisl</a></li>\r\n");
      out.write("                                 </ul>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li><a href=\"#\">Veroeros feugiat</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"menu_myPage.jsp\">마이페이지</a></li>\r\n");
      out.write("                        <!-- <li><a href=\"login/login.jsp\">로그인</a></li> : 이미 로그인 해서 없어도 될 것 같음 -->\r\n");
      out.write("                        ");
if(info !=null){ 
      out.write("\r\n");
      out.write("                        <li><a href=\"../LogoutService\">로그아웃</a></li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </nav>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- Main -->\r\n");
      out.write("            <div class=\"wrapper style1\">\r\n");
      out.write("\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row gtr-200\">\r\n");
      out.write("                     <div class=\"col-4 col-12-mobile\" id=\"sidebar\">\r\n");
      out.write("                        <section>\r\n");
      out.write("                           <header>\r\n");
      out.write("                              <h3><a href=\"#\" id=\"mypageLink\">MY PAGE</a></h3>\r\n");
      out.write("                           </header>\r\n");
      out.write("                           <br>\r\n");
      out.write("                           <div class=\"row gtr-50\">\r\n");
      out.write("                              <div class=\"col-8\">\r\n");
      out.write("                                 <a href=\"#\" class=\"image fit\" id=\"modifyLink\"><h4>MODIFY</h4></a>                              \r\n");
      out.write("                              </div>\r\n");
      out.write("                              \r\n");
      out.write("                              <div class=\"col-8\">\r\n");
      out.write("                                 <a href=\"#\" class=\"image fit\" id=\"scheduleLink\"><h4>SCHEDULE</h4></a>                           \r\n");
      out.write("                              </div>\r\n");
      out.write("                              \r\n");
      out.write("                              <div class=\"col-8\">\r\n");
      out.write("                                 <a href=\"#\" class=\"image fit\" id='badgeLink'><h4>BADGE</h4></a>\r\n");
      out.write("                              </div> \r\n");
      out.write("                           </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"col-8 col-12-mobile imp-mobile\" id=\"content\">\r\n");
      out.write("                        <article id=\"main\">\r\n");
      out.write("                        	<div id=\"myPageScreen\">\r\n");
      out.write("						  	   <header><h3>");
      out.print(info.getNick() );
      out.write("님 환영합니다!</h3></header>\r\n");
      out.write("                           	   <a href=\"#\" class=\"image featured\"><img src=\"images/pic06.jpg\" alt=\"\" /></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<script>\r\n");
      out.write("							document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    							// \"MY PAGE\" 텍스트를 클릭 시 이벤트 생성\r\n");
      out.write("    							function showMyPageScreen() {\r\n");
      out.write("        							document.getElementById('myPageScreen').style.display = 'block';\r\n");
      out.write("       								document.getElementById('modifyScreen').style.display = 'none';\r\n");
      out.write("       								document.getElementById('scheduleScreen').style.display = 'none';\r\n");
      out.write("        							document.getElementById('badgeScreen').style.display = 'none';\r\n");
      out.write("    							}\r\n");
      out.write("    							// \"MY PAGE\" 링크 요소를 가져오기\r\n");
      out.write("   								 var mypageLink = document.getElementById('mypageLink');\r\n");
      out.write("\r\n");
      out.write("   								// \"MY PAGE\" 링크 요소에 클릭 이벤트 등록\r\n");
      out.write("   								 mypageLink.addEventListener('click', function(event) {\r\n");
      out.write("       								 event.preventDefault();\r\n");
      out.write("      								  // MY PAGE 화면을 보이도록 함수를 호출합니다.\r\n");
      out.write("        							 showMyPageScreen();\r\n");
      out.write("   								 });\r\n");
      out.write("							});\r\n");
      out.write("							</script>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("								<div id=\"modifyScreen\" style=\"display: none;\">\r\n");
      out.write("									<header>MODIFY</header>\r\n");
      out.write("									<form action=\"../UpdateService\" method=\"post\">\r\n");
      out.write("									<div class=\"form-field\">\r\n");
      out.write("										<label for=\"password\">Password</label> \r\n");
      out.write("										<input name=\"pw\" type=\"password\" id=\"password\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<br>\r\n");
      out.write("									<div class=\"form-field\">\r\n");
      out.write("										<label for=\"nick\">NickName</label> <input name=\"nick\"\r\n");
      out.write("											type=\"text\" id=\"nick\"> <span id=\"nickCheck\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<br>\r\n");
      out.write("									<button type=\"submit\" class=\"btn-update\">UPDATE</button>\r\n");
      out.write("								</form>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<!-- 닉네임 중복 -->\r\n");
      out.write("								<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>	\r\n");
      out.write("								\r\n");
      out.write("								<script type=\"text/javascript\">\r\n");
      out.write("     							$(window).load(function(){\r\n");
      out.write("           \r\n");
      out.write("          	 					$(\"#nick\").keyup(function(){\r\n");
      out.write("              						const nickCheck = document.getElementById(\"nickCheck\");\r\n");
      out.write("              						let inputNick = $(\"#nick\").val();\r\n");
      out.write("              \r\n");
      out.write("         \r\n");
      out.write("              						$.ajax({\r\n");
      out.write("                 						url : \"../nickCheck\",\r\n");
      out.write("                 						data : {\"nick\" : inputNick},\r\n");
      out.write("                 						success : function(text){\r\n");
      out.write("                    					if(text===\"true\"){\r\n");
      out.write("                          					nickCheck.innerText = \"중복된 닉네임입니다.\";\r\n");
      out.write("                    					}else{\r\n");
      out.write("                       						nickCheck.innerText = \"사용 가능한 닉네임입니다.\";\r\n");
      out.write("                    					}\r\n");
      out.write("                 						},\r\n");
      out.write("                 						error : function(e){\r\n");
      out.write("                    						console.log(e);\r\n");
      out.write("                 						}\r\n");
      out.write("              							});   \r\n");
      out.write("           							});\r\n");
      out.write("        						});\r\n");
      out.write("\r\n");
      out.write("     							\r\n");
      out.write("							    // 페이지 로딩 완료 시 이벤트를 등록\r\n");
      out.write("								document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("   								// \"MODIFY\" 텍스트를 클릭 시 정보 수정 창 보임\r\n");
      out.write("   								 	function showModifyScreen() {\r\n");
      out.write("        								document.getElementById('modifyScreen').style.display = 'block';\r\n");
      out.write("    								}\r\n");
      out.write("    							// \"MODIFY\" 링크 요소를 가져옵니다.\r\n");
      out.write("    							var modifyLink = document.getElementById('modifyLink');\r\n");
      out.write("\r\n");
      out.write("    							// \"MODIFY\" 링크 요소에 클릭 이벤트를 등록\r\n");
      out.write("    							modifyLink.addEventListener('click', function(event) {\r\n");
      out.write("       							 	// 기본 동작 (링크 이동)을 취소합니다.\r\n");
      out.write("       							 	event.preventDefault();\r\n");
      out.write("        							// 정보 수정 화면을 보이도록 함수 호출 + myPageScreen 숨김\r\n");
      out.write("        							showModifyScreen();\r\n");
      out.write("        							myPageScreen.style.display = 'none';\r\n");
      out.write("        							scheduleScreen.style.display='none';\r\n");
      out.write("        							badgeScreen.style.display = 'none';\r\n");
      out.write("    								});\r\n");
      out.write("								});\r\n");
      out.write("								</script>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								<div id=\"scheduleScreen\" style=\"display: none;\">\r\n");
      out.write("									<header>SCHEDULE</header>\r\n");
      out.write("									<!-- 일정 페이지 -->\r\n");
      out.write("									<br>\r\n");
      out.write("									<!--   <form action=\"#\" method=\"post\"> -->\r\n");
      out.write("									<div id=\"scheduleContainer\">\r\n");
      out.write("										<div class=\"schedule-list\">\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><label><input type=\"radio\" name=\"mem_schedule\"\r\n");
      out.write("														value=\"schedule1\" class=\"radio-button\"><a href=\"#\"\r\n");
      out.write("														class=\"scheduleLink\">어떤 식당 > 어떤 박물관 > 어떤 해안가 > 어떤 카페</a></label></li>\r\n");
      out.write("												<li><label><input type=\"radio\" name=\"mem_schedule\"\r\n");
      out.write("														value=\"schedule2\" class=\"radio-button\"><a href=\"#\"\r\n");
      out.write("														class=\"scheduleLink\">무슨 식당 > 어디해안가 > 어디 식당</a></label></li>\r\n");
      out.write("												<li><label><input type=\"radio\" name=\"mem_schedule\"\r\n");
      out.write("														value=\"schedule3\" class=\"radio-button\"><a href=\"#\"\r\n");
      out.write("														class=\"scheduleLink\">한라산 > 스타벅스 > OO식물원 > 제주공항</a></label></li>\r\n");
      out.write("																											\r\n");
      out.write("											</ul>\r\n");
      out.write("											<div class=\"recommend-btn\">\r\n");
      out.write("												<button id=\"recommendButton\">일정추천</button>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"schedule-comment\" style=\" display:none;\">\r\n");
      out.write("												<div class=\"comment-content\">\r\n");
      out.write("												<h3>한줄평 작성</h3>\r\n");
      out.write("												 <textarea id=\"reviewTextArea\" class=\"review-textarea\" placeholder=\"한줄평을 작성해주세요...\"></textarea>\r\n");
      out.write("                                      			 <div class=\"submit-review\">\r\n");
      out.write("                                          		<button type=\"submit\" value=\"comment\" id=\"submitReviewButton\">작성 완료</button>\r\n");
      out.write("												</div>	\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"schedule-map\" id=\"mapContainer\" style=\"display:none;\">\r\n");
      out.write("											<div id=\"map\" style=\"width:350px;height:350px;\"></div>\r\n");
      out.write("											<script type=\"text/javascript\"\r\n");
      out.write("												src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=f93746e33ed79e4637c2a1c0f03f736a\"></script>\r\n");
      out.write("											<script>\r\n");
      out.write("												var container = document.getElementById('map');\r\n");
      out.write("												var options = {\r\n");
      out.write("													center : new kakao.maps.LatLng(35.1466, 126.9223),\r\n");
      out.write("													level : 3\r\n");
      out.write("												};\r\n");
      out.write("\r\n");
      out.write("												var map = new kakao.maps.Map(container, options);\r\n");
      out.write("\r\n");
      out.write("												// 마커가 표시될 위치입니다 \r\n");
      out.write("												var markerPosition = new kakao.maps.LatLng(35.1466, 126.9223);\r\n");
      out.write("\r\n");
      out.write("												// 마커를 생성합니다\r\n");
      out.write("												var marker = new kakao.maps.Marker(\r\n");
      out.write("														{\r\n");
      out.write("															position : markerPosition\r\n");
      out.write("														});\r\n");
      out.write("\r\n");
      out.write("												// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("												marker.setMap(map);\r\n");
      out.write("											</script>\r\n");
      out.write("										</div>\r\n");
      out.write(" \r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- </form> -->\r\n");
      out.write("									</div>\r\n");
      out.write("									<script>\r\n");
      out.write("    									const recommendButton = document.getElementById('recommendButton');\r\n");
      out.write("    									const commentSection = document.querySelector('.schedule-comment');\r\n");
      out.write("    									const closeButton = document.getElementById('closeButton');\r\n");
      out.write("\r\n");
      out.write("    									recommendButton.addEventListener('click', () => {\r\n");
      out.write("    								        // recommendButton 버튼을 감추기\r\n");
      out.write("    								        recommendButton.style.display = 'none';\r\n");
      out.write("        									// 선택한 일정에 대한 한줄평 작성 영역을 보이게 설정\r\n");
      out.write("        									commentSection.style.display = 'block';\r\n");
      out.write("    									});\r\n");
      out.write("    								\r\n");
      out.write("    									\r\n");
      out.write("\r\n");
      out.write("    									// submitReviewButton 클릭 이벤트 등의 코드\r\n");
      out.write("									</script>\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								<script>\r\n");
      out.write("								document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("   								 	function showScheduleScreen() {\r\n");
      out.write("        								document.getElementById('scheduleScreen').style.display = 'block';\r\n");
      out.write("    								}\r\n");
      out.write("    							var scheduleLink = document.getElementById('scheduleLink');\r\n");
      out.write("\r\n");
      out.write("    							scheduleLink.addEventListener('click', function(event) {\r\n");
      out.write("       							 	event.preventDefault();\r\n");
      out.write("        							showScheduleScreen();\r\n");
      out.write("        							\r\n");
      out.write("       						        var scheduleContainer = document.getElementById('scheduleContainer');\r\n");
      out.write("\r\n");
      out.write("       						        if (scheduleContainer.style.display === 'none') {\r\n");
      out.write("       						        	scheduleContainer.style.display = 'block'; \r\n");
      out.write("       						        }        							\r\n");
      out.write("        							\r\n");
      out.write("        							myPageScreen.style.display = 'none';\r\n");
      out.write("        							modifyScreen.style.display = 'none';\r\n");
      out.write("        							badgeScreen.style.display = 'none';\r\n");
      out.write("        							\r\n");
      out.write("    								});\r\n");
      out.write("								});\r\n");
      out.write("								</script>\r\n");
      out.write("								<script>\r\n");
      out.write("								document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("   									var scheduleLinks = document.querySelectorAll('.scheduleLink');\r\n");
      out.write("\r\n");
      out.write("   							 		scheduleLinks.forEach(function(link) {\r\n");
      out.write("        								link.addEventListener('click', function(event) {\r\n");
      out.write("           							 		event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            								var mapContainer = document.getElementById('mapContainer');\r\n");
      out.write("\r\n");
      out.write("            								if (mapContainer.style.display === 'none') {\r\n");
      out.write("                								mapContainer.style.display = 'block';\r\n");
      out.write("            								} else {\r\n");
      out.write("                								mapContainer.style.display = 'none';\r\n");
      out.write("            								}\r\n");
      out.write("        										});\r\n");
      out.write("    										});\r\n");
      out.write("										});\r\n");
      out.write("								</script>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								<div id=\"badgeScreen\" style=\"display: none;\">\r\n");
      out.write("									<header>BADGE</header>\r\n");
      out.write("									<!-- 뱃지 페이지 -->\r\n");
      out.write("									<br>\r\n");
      out.write("									<div id=\"imageContainer\" style=\"display: none;\">\r\n");
      out.write("										<div class=\"badge-list\">\r\n");
      out.write("										");
      out.write("\r\n");
      out.write("											<ul>\r\n");
      out.write("												");
if(info!=null){ 
      out.write("\r\n");
      out.write("												");

													BadgeDAO dao = new BadgeDAO();
												
													ArrayList<BadgeDTO> list = dao.badge(info.getId());
													
													for(int i = 0; i < list.size(); i++){
														out.print("<li>");
														out.print("<div class=\"img-area\">");
														out.print("<img src='" + list.get(i).getBadge_img() + "' alt=''/>");
														out.print("</div>");
														out.print("<span class='tit'>" + list.get(i).getBadge_name() + "</span>");	
													}}
      out.write("\r\n");
      out.write("													\r\n");
      out.write("										\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"img-area\">\r\n");
      out.write("														<img src=\"ham.jpg\" alt=\"\" />\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"tit\">브이커햄</span>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"img-area\">\r\n");
      out.write("														<img src=\"ham.jpg\" alt=\"\" />\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"tit\">브이커햄</span>\r\n");
      out.write("												</li>											\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"img-area\">\r\n");
      out.write("														<img src=\"tin.png\" alt=\"\" />\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"tit\">틴틴팅클</span>\r\n");
      out.write("												</li>											\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"img-area\">\r\n");
      out.write("														<img src=\"tin.png\" alt=\"\" />\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"tit\">틴틴팅클</span>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"img-area\">\r\n");
      out.write("														<img src=\"tin.png\" alt=\"\" />\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"tit\">틴틴팅클</span>\r\n");
      out.write("												</li>																						\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div> \r\n");
      out.write("									</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								<script>\r\n");
      out.write("								document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("   								 	function showBadgeScreen() {\r\n");
      out.write("        								document.getElementById('badgeScreen').style.display = 'block';\r\n");
      out.write("    								}\r\n");
      out.write("    							var badgeLink = document.getElementById('badgeLink');\r\n");
      out.write("\r\n");
      out.write("    							badgeLink.addEventListener('click', function(event) {\r\n");
      out.write("       							 	event.preventDefault();\r\n");
      out.write("       							 	showBadgeScreen();\r\n");
      out.write("       							 	\r\n");
      out.write("       						        // 이미지들을 담고 있는 div 요소를 가져옵니다.\r\n");
      out.write("       						        var imageContainer = document.getElementById('imageContainer');\r\n");
      out.write("\r\n");
      out.write("       						        if (imageContainer.style.display === 'none') {\r\n");
      out.write("       						            imageContainer.style.display = 'block'; // 보이도록 설정\r\n");
      out.write("       						        }\r\n");
      out.write("       							 	\r\n");
      out.write("        							myPageScreen.style.display = 'none';\r\n");
      out.write("        							modifyScreen.style.display = 'none';\r\n");
      out.write("        							scheduleScreen.style.display = 'none';\r\n");
      out.write("        							\r\n");
      out.write("    								});\r\n");
      out.write("								});\r\n");
      out.write("								</script>								\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </article>\r\n");
      out.write("						</div>\r\n");
      out.write("								\r\n");
      out.write("                  \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- Footer -->\r\n");
      out.write("            <div id=\"footer\">\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <hr />\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-12\">\r\n");
      out.write("\r\n");
      out.write("                 <!-- Contact -->\r\n");
      out.write("                           <section class=\"contact\">\r\n");
      out.write("                              <header>\r\n");
      out.write("                                 <h3>나만의 여행, PPLAN</h3>\r\n");
      out.write("                              </header>\r\n");
      out.write("                              <p>TROPHY</p>\r\n");
      out.write("                              <ul class=\"icons\">\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-pinterest\"><span class=\"label\">Pinterest</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-linkedin-in\"><span class=\"label\">Linkedin</span></a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Copyright -->\r\n");
      out.write("                           <div class=\"copyright\">\r\n");
      out.write("                              <ul class=\"menu\">\r\n");
      out.write("                                 <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Scripts -->\r\n");
      out.write("         <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
